# Generated by Django 4.1 on 2022-09-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyWatchList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("films_watched", models.TextField()),
                ("films_title", models.TextField()),
                ("films_rating", models.IntegerField()),
                ("films_release_date", models.TextField()),
                ("films_review", models.TextField()),
            ],
        ),
    ]
